apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: poet-test-
spec:
  entrypoint: argo-poet
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: nfs-2
  arguments:
    parameters:
      - name: nFiles
        value: 10
      - name: nSteps
        value: 1
      - name: recid
        value: 24119
  templates:
    - name: argo-poet
      inputs:
        parameters:
          - name: nFiles
          - name: nSteps
          - name: recid
      dag:
        tasks:
          - name: prepare
            template: prepare-template

          - name: filelist
            dependencies: [prepare]
            template: filelist-template
            arguments:
              parameters:
                - name: nFiles
                  value: "{{inputs.parameters.nFiles}}"
                - name: nSteps
                  value: "{{inputs.parameters.nSteps}}"
                - name: recid
                  value: "{{inputs.parameters.recid}}"

          - name: runpoet
            dependencies: [filelist]
            template: runpoet-template
            arguments:
              parameters:
                - name: nFiles
                  value: "{{inputs.parameters.nFiles}}"
                - name: recid
                  value: "{{inputs.parameters.recid}}" 

    # prepare the data directories needed in the workflow steps
    - name: prepare-template
      script:
        image: ubuntu:latest
        command: [bash]
        source: |
          mkdir -p /mnt/vol/data
          mkdir -p /mnt/vol/code
          chmod -R 777 /mnt/vol
        volumeMounts:
          - name: task-pv-storage
            mountPath: /mnt/vol  

    # get the full list of files and write the files to be processed to a file
    - name: filelist-template
      inputs:
        parameters:
          - name: nFiles
          - name: nSteps
          - name: recid
      script:
        image: cernopendata/cernopendata-client
        command: [bash]
        source: |
          cernopendata-client get-file-locations --recid "{{inputs.parameters.recid}}" --protocol xrootd > /mnt/vol/files_{{inputs.parameters.recid}}.txt;
          nFiles="{{inputs.parameters.nFiles}}"
          echo $nFiles
          head -$nFiles /mnt/vol/files_{{inputs.parameters.recid}}.txt > /mnt/vol/data/step_files_{{inputs.parameters.recid}}.txt
          echo Selected files:
          cat /mnt/vol/data/step_files_{{inputs.parameters.recid}}.txt
        volumeMounts:
          - name: task-pv-storage
            mountPath: /mnt/vol

    # prepare the data directories needed in the workflow steps
    - name: runpoet-template
      inputs:
        parameters:
        - name: recid
        - name: nFiles
      script:
        image: cmsopendata/cmssw_7_6_7-slc6_amd64_gcc493
        command: [bash]
        source: |
          sudo chown $USER /mnt/vol
          source /opt/cms/entrypoint.sh
          git clone -b odws2022-ttbaljets-prod https://github.com/katilp/PhysObjectExtractorTool.git
          cd PhysObjectExtractorTool/PhysObjectExtractor
          scram b
          echo "{{inputs.parameters.nFiles}}"
          echo "/mnt/vol/files_{{inputs.parameters.recid}}.txt"
          cmsRun python/poet_cfg.py True "{{inputs.parameters.nFiles}}" 1 "/mnt/vol/files_{{inputs.parameters.recid}}.txt"
          mv myoutput.root /mnt/vol/output_{{inputs.parameters.recid}}.root
        volumeMounts:
        - name: task-pv-storage
          mountPath: /mnt/vol