apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: poet-test-
spec:
  entrypoint: argo-poet
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: nfs-2
  arguments:
    parameters:
      - name: nFiles
        value: 1
      - name: recid
        value: |
          [
            {"recid": 24119}
          ] 
      - name: nJobs
        value: 1       
  templates:
    - name: argo-poet
      inputs:
        parameters:
          - name: nFiles
          - name: nJobs
          - name: recid
      dag:
        tasks:
          - name: mergetrees
            template: mergetrees-template
            arguments:
              parameters: 
                - name: recid
                  value: "{{item.recid}}"
            withParam: "{{inputs.parameters.recid}}"

    # merge trees
    - name: mergetrees-template
      inputs:
        parameters:
          - name: recid
      script:
        image: gitlab-registry.cern.ch/cms-cloud/python-vnc:latest
        command: [bash]
        source: |
          echo "-l /mnt/vol/output/{{inputs.parameters.recid}}/:""
          ls -l /mnt/vol/output/{{inputs.parameters.recid}}/
          echo "Going to run: python /mnt/vol/code/merge_trees.py /mnt/vol/output/{{inputs.parameters.recid}}/"
          python /mnt/vol/code/merge_trees.py /mnt/vol/output/{{inputs.parameters.recid}}/
        volumeMounts:
          - name: task-pv-storage
            mountPath: /mnt/vol