apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: coffea-test-
spec:
  entrypoint: argo-coffea
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: nfs-2
  arguments:
    parameters:
      - name: aParameter
        value: "parameter value"
  templates:
    - name: argo-coffea
      inputs:
        parameters:
          - name: aParameter
      dag:
        tasks:
          - name: prepare
            template: prepare-template

          - name: commands
            dependencies: [prepare]
            template: commands-template

          - name: runcoffea
            dependencies: [commands]
            template: runcoffea-template

    # prepare the data directories needed in the workflow steps
    - name: prepare-template
      script:
        image: ubuntu:latest
        command: [bash]
        source: |
          mkdir -p /mnt/vol/data
          mkdir -p /mnt/vol/code
          mkdir -p /mnt/vol/full
          chmod -R 777 /mnt/vol
        volumeMounts:
          - name: task-pv-storage
            mountPath: /mnt/vol  

    - name: commands-template
      script:
        image: ubuntu:latest
        command: [bash]
        source: |
          echo "pip install vector hist mplhep coffea" > /mnt/vol/code/commands.sh
          echo "git clone https://github.com/cms-opendata-workshop/workshop2022-lesson-ttbarljetsanalysis-payload.git" >> /mnt/vol/code/commands.sh
          echo "cd workshop2022-lesson-ttbarljetsanalysis-payload" >> /mnt/vol/code/commands.sh
          echo "python coffeaAnalysis_ttbarljets.py" >> /mnt/vol/code/commands.sh
          echo "mv *root /mnt/vol/full" >> /mnt/vol/code/commands.sh
          echo "mv *png /mnt/vol/full" >> /mnt/vol/code/commands.sh
          cat /mnt/vol/code/commands.sh
        volumeMounts:
          - name: task-pv-storage
            mountPath: /mnt/vol 

    # prepare the data directories needed in the workflow steps
    - name: runcoffea-template
      script:
        image: gitlab-registry.cern.ch/cms-cloud/python-vnc:latest
        command: [bash, /mnt/vol/code/commands.sh]
        volumeMounts:
        - name: task-pv-storage
          mountPath: /mnt/vol